### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by DemonfangArun** [TheCBProject/ForgeMultipart#76]
I'm having a lovely day -.-

https://paste.dimdev.org/olofalareg.mccrash

Forge x.2847

I'm not sure where to start with this, updated a bunch of things, this mod wasn't one, and now this.

**Comment by SShinkun** [comment]
What mods did you update? 
I recommend rolling back these updates if you remember (if I understand correctly it happened because of that) and seeing if it works then, it's possible the change made in an update changes compatibility with other mods.

**Comment by DemonfangArun** [comment]
And the funny part is this error occurred once, and then never again, despite changing nothing. I've decided to leave it for further investigation. My best guess is something loading in a weird way or out of order.

**Comment by covers1624** [comment]
`dimdev.org` is down. I highly encourage everyone to use [gist](https://gist.github.com), GitHub's own service for pasting things.

**Comment by DemonfangArun** [comment]
Well I apologize for not knowing it went down since last I used it. I am also not the developer of VanillaFix, which generates these reports, so telling "ME" to use a different site would be better redirected there.

It's also possible it's temporary, everything is overloaded, and it's not like github hasn't been down before.

Your reason for closing this is questionable at best, and I will keep it in mind going forward when choosing mods.

**Comment by covers1624** [comment]
Immediately instead of providing me with a crash report I can actually access and help fix whatever issue you are having, you go on the defensive. If you don't want to use my mods, go for it, that's your decision, no one is forcing you to, your vaigue threat of removing my mods from your pack does nothing to sway my judgment. Please provide a useable crash report, or this issue will stay closed.

**Comment by DemonfangArun** [comment]
And that crash report was generated 1.5 months ago, and that link was the only copy, I don't keep an archive of them, and I doubt 99% do. I'm not going out of my way to use some service I've never heard of before now, let alone 1.5 months ago, because I magically know that what I'm using is going to have some downtime in the future rendering it inaccessible.

That said, I will make a suggestion to vanillafix devs to perhaps add an option to select a site, assuming gist has an API that can be used.

**Comment by DemonfangArun** [comment]
It looks like gist requires an account to use, so that wouldn't be suitable for automation

It also appears that the above site is now back up from its temporary outage, so your reason for closing this ticket is now null.

**Comment by SShinkun** [comment]
Since I've been receiving emails of this thread and thus your pointless rambling, allow me to point out that not only is Forge Multipart a free service that people are working on in their free time without charging you a dime, they are also asking you to merely create dummy account on a different service which even if you had a good reason not to do can be substituted by a service such as hastebin.
Yet all you have been doing for the past 3 messages is bitch about.
In this same time you could have opened a new thread, posted your log using a different temporary file service and actually gotten your issue looked at.
I sincerely hope you don't think that this behaviour will get you any help because you would be severely deceiving yourself, I would take myself as an example but since you stated your a developer too; you can't make me believe that if anyone sent you an issue report or any other kind of communication like this that you wouldn't immediately toss it in the bin.

Apparently Covers is either too polite to tell you this or has ignored the thread at this point which I would not blame him a second for.
If you want support try being decent.

**Comment by DemonfangArun** [comment]
Yes, I understand it's free, and I do understand the time that is put into it at no cost to me or anyone else for everyone to use, same as most mods.

What I don't appreciate is being told to use a different service than one I've already been using because of a temporary outage and having tickets closed on me. That says to me "use this service to post logfiles or I'm not working with you" which is a bit snobby and will make me not want to interact with you or your projects in the future. I don't keep crash reports for months on end, at most it'll stick around for a week unless it's a persistent gamebreaking bug, which this wasn't (as it only happened once).

As for how I would handle the above, I would mark it to come back to later when the service came back online, because I understand that websites go down from time to time, even Google is not immune to this.

**Comment by covers1624** [comment]
Ahh fantastic it's back up. That's a crash I have never seen before, I suspect something cross-thread related was happening during startup. At any rate, the offending code there has been nuked in 1.15 and as that is my main focus right now, there won't be any fixes for 1.12. Since this was reported as a one time crash, I'm going to leave this closed.  

As for the Off-topic talk here, gist only requires a GitHub account, HasteBin, as mentioned, is another good example (PasteBin too). As for the 'mark and come back later', that is exactly what I did, even though I didn't say that in my original reply, and probably should have, but I don't feel I should have to validate my reasons for closing issues to people, I closed it, that was the reason, Instead of replying as you did a more calm rational manner something along the lines of, 'Ah shit, any chance you can wait for it to come back up?' would have been, In my eyes, more acceptable. Frankly, the only reason I'm following this up is because the site came back up. Whilst I agree with some of the points @SShinkun brings up, I don't agree with the general tone. Overall I think you approached your replies here in a childish entitled manner, but I'm overlooking that because I choose to. As for you not using my mods, communicating with me, >insert thing here<, I honestly don't care, what you do has no impact on me. I'm providing a free service here, something I do in my spare time as a hobby alongside my actual job, The service you get, is what you get, I'm not a company. o/
