### ISSUE TITLE
java.lang.NullPointerException: Rendering item (Description: Rendering item)

### ISSUE THREAD

**Issue by phlopsi** [TheCBProject/ForgeMultipart#8]
And another client crash. Different one again: https://paste.ee/p/KbdYC
Same good old image: https://i.imgur.com/QPYeFwq.png

**Comment by covers1624** [comment]
Paste has expired : https://github.com/TheCBProject/Feedback

**Comment by phlopsi** [comment]
It's not like you would've fixed anything, anyway. Your lack of reaction towards crash reports is just dissappointing and since you just closed it immediately instead of asking, if I was still having these crash reports and if I could re-upload them, it makes me believe you waited on purpose, so this issue solves itself, because you just don't want to be bothered by it.

I am a very understanding person when it comes to lack of time due to other priorities. I have seen you commitment on other projects and a simple reply, like: "Sorry, but I am currently busy overhauling/updating another mod and can't attend to this issue anytime soon.", would've been fine and something I expect of people, who decide to take a certain amount of responsibility on themselves. However, in your case, nothing happend in ~1.5 months, while still being active in the modding scene, overall.

Finding this repository in the first place to be able to send you any issues, was already difficult, since no link exists on platforms where you distribute the mod. The reason seems to be, that you simply don't care about the mod, if you decide to simply ignore any created issues, like these.

Really sad to see mods with a great potential like these and other mods depending on it, just being unplayable due to lack of support.

**Comment by covers1624** [comment]
Wowah, take a step back and take another look at the situation please. Since this issue was reported there have been several commits to FMP fixing issues with rendering, The reason i wasn't active with FMP is Tj was doing stuff at the time this was reported and i had no time as i was working on other things, when i finally got time to look at issues, i closed all the old ones and told people to create new issues under the central tracker if their issue persists. What makes me more certain your issue is fixed is the fact that A, you were the only one having the issue, B, You have lots of parts spanning lots of chunks and threaded rendering was recently fixed for the microblock section of FMP. If you noticed it wasn't just FMP i was dragged away from, it was all the projects i maintain, motivation is a tricky thing to feather and getting the balance right is a difficult thing, I've been working on CB's stuff for over a year now there have been several instances where i momentarily had no motivation, recently I've found a good game to binge from time to time and help drag that motivation back every day by taking small breaks away from coding so i don't burn myself out. That was a personal issue that is now solved. Now the reason i closed it was, A, paste expired and i can't do anything about that. B, I was in the middle of migrating to the central repo and just closed it hoping that if you had the issue again (as you weren't active on the issues saying, "Any news this is still happening") you would open a new issue with an updated crash report, C, As i said before threaded rendering was recently fixed and i just assumed as you weren't active here that it had been resolved.

**Comment by phlopsi** [comment]
I waited about 2 weeks for a reply or any updates for FMP, checked on a daily basis, but there was literally nothing. Since this mod in combination with Project Red was my biggest motivation to start playing Minecraft with my friends again and removing all microblocks to be able to run the server took away most of this motivation from me, my only choice was, sadly, dropping Minecraft again.

While I'm proficient with Java and I had modding experience from the past, i.e. I can generally fix these kind of issues, at least to a degree of it not crashing anymore, I was (and still am) busy developing a mod with a bigger team for another game. Since we are required to deliver next month, I simply didn't have time to invest even more time in modding other games, than I already do for my own. That extra time I reserved, was supposed to be a break for me, not more work.

Now, nearing the finishing line of the release, I'm too busy playing anything, so what it boils down to, is that, when I had time to enjoy Minecraft with mods, I couldn't and now, that this issue has apparently been fixed, I don't have the time to play, anymore.

I apologize for getting too emotional, but I hope you understand **why** I'm so frustrated. When the mod I'm working on, is finally released, I'll take you upon your word, that this issue has very likely been fixed and will try playing with it again. I'll keep reporting issues, when I do, but please, at least reply, even if it's just a "Can you update FMP/CB and look, if it still works?" or "Currently, I don't have the time to look at it. I won't be able to investigate this issue before <e.g. next month>.". I would really appreciate that.

Thank you for explaining me your situation, as well.
