### ISSUE TITLE
[1.12.2] Concurrent modification triggered by `autoCompleteJavaTrait` creating new ObfRemapper

### ISSUE THREAD

**Issue by noobanidus** [TheCBProject/ForgeMultipart#80]
I know that there was a previous issue filed with this but the reporter was a little bit of a jerk. Sorry you had to deal with someone like that! I understand from the thread that the code in question is something that has changed in 1.15, but unfortunately my friends' server has *recently* begun to crash with this concurrent modification error **seemingly intermittently** upon start up, and then eventually after the server has started, after the server had to be stopped following a lock-up caused by an out-of-memory issue.

Specificially, [here is the relevant section from the](https://gist.github.com/noobanidus/9ab42a48d68785ef83e63823d9fd0d0c). I've gone through the rest of the log and the only lines relevant to codechicken or multipart are a) the minecraft multipart plug-in, and the standard mcmod.info identification & loading and mod container creation for both codechicken and multipart. If you wish the entire debug log, I can provide it for you.

[Here is the crash report](https://gist.github.com/noobanidus/9404109baa13301c64c75a2c4f213fe4) in its entirety with all the relevant information.

What confuses me the most about this is it appears to be [from this line in ObfRemapper](https://github.com/TheCBProject/CodeChickenLib/blob/1.12.x/src/main/java/codechicken/lib/reflect/ObfMapping.java) which unfortunately doesn't really help as the line numbers in the crash report don't match up properly with the current version of CCL's ObfMapping.java that I can see.

Outside of a threading issue, which seems unlikely given the fact that 1.12.2's initialization is all done synchronously, I'm not really sure what could be causing the issue based on the crash report. It's obvious that, for some reason, the actual looping over the values is what's triggering it (based on `HashIterator.nextNode` being the default method used for the `EntryIterator` from `entrySet`), implying that those are the values being accessed by something else.

There is the `DeobfuscationTransformer` (I haven't done much work with ASM in 1.12.2) which, hypothetically, if it were to cause a class-load of the multipart ASM while it was also deobfuscating or performing some sort of remapping... but that seems like a bit of a stretch.

But the fact that sometimes it loads without issue but then crashes is bothering me -- I thought I had a lot file indicating that it was crashing with the concurrent modification issue, but perhaps it's something else...

Either way, this error tends to occur multiple times on start-up. [Here's the full debug log of at least one instance where the crash occurs, if it's helpful to you](https://gist.github.com/noobanidus/97ddc4488cd3988383752343121d4308).

Obviously, I understand that this isn't a version you're currently working on, and if it's something that you're not supporting, that's totally fine! I just hoped you might have some thoughts or ideas as to why this has recently started occurring.

**Comment by covers1624** [comment]
Interesting! FMP there isn't using CCL's ObfMapping, it's using ChickenASM's, found [here](https://github.com/TheCBProject/ChickenASM/blob/ec95c0b9f1248e4d921ca5bbec6c32738f4e02bb/src/main/java/codechicken/asm/ObfMapping.java). Once we can look at line numbers, we can see its the `fawFieldsMap` From the stack trace, it's already loaded classes, and the jvm is initializing classes now, due to the single thread nature of LaunchWrapper, it shouldn't be loading any classes as we are initializing `ObfRemapper`. Perhaps another thread is remapping stuff, I have no idea, and yes this doesn't apply to 1.15, but if your feeling up to it, you can modify ChickenASM yourself and attempt to fix it, but the jar-in-jar system is largely undocumented sadly, Feel free to message me on discord if you have any questions about that route.

**Comment by covers1624** [comment]
Some initial thoughts for a fix would be, to have [SnifferTransformer](https://github.com/TheCBProject/ChickenASM/blob/ec95c0b9f1248e4d921ca5bbec6c32738f4e02bb/src/main/java/codechicken/asm/internal/SnifferTransformer.java#L9) create an empty instance of ObfMapping, in its constructor, in order to initialize it _really_ early on. Or to just not throw a RuntimeException there if it breaks.
